CREATE TABLE buildings (bID VARCHAR2(10),bName VARCHAR2(100),numVertices NUMBER,shape SDO_GEOMETRY,PRIMARY KEY (bID));
CREATE TABLE fire_buildings (fname VARCHAR2(100));
CREATE TABLE hydrants (hID VARCHAR2(10),shape SDO_GEOMETRY,PRIMARY KEY (hID));
INSERT INTO user_sdo_geom_metadata(TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)VALUES ('buildings','shape',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 0, 1000, 0.005),SDO_DIM_ELEMENT('Y', 0, 1000, 0.005)),NULL);
CREATE INDEX buildings_idx ON buildings(shape) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
INSERT INTO user_sdo_geom_metadata(TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)VALUES ('hydrants','shape',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 0, 1000, 0.005),SDO_DIM_ELEMENT('Y', 0, 1000, 0.005)),NULL);
CREATE INDEX hydrants_idx ON hydrants(shape) INDEXTYPE IS MDSYS.SPATIAL_INDEX;